### ISSUE TITLE
Не работает ни zip/ ни unzip , ниодин архив не распаковывается

### ISSUE THREAD

**Issue by nepohex** [coderaiser/cloudcmd#100]
Загрузил 5 разных архивов с одним файлом, ниодин из них не получилось распаковать:
zip
tar
gz
7z

Когда пробовал TAR так вообще в Putty ошибка вылезла
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
    at Object.exports.decode (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/headers.js:265:40)
    at Extract.onheader (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:120:39)
    at Extract._write (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:243:8)
    at Extract._continue (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:207:28)
    at oncontinue (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:64:10)
    at Extract.onheader (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:128:7)
    at Extract._write (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:243:8)
    at doWrite (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at Extract.Writable.write (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/_stream_writable.js:274:11)

После этого перезапустил, все работает как обычно.

Также словил баг -  нажал на CONFIG кнопку внизу, и теперь вообще запустить не могу сам менеджер - пишет 

[root@vps110392 json]# cloudcmd
cloudcmd --port: listen EADDRINUSE 0.0.0.0:9113

(до этого работало отлично на порте который я указал 9113).

Как теперь поправить, удалить или что-то сделать - не понятно. Просмотрел все конфиги в папке /usr/lib/node_modules/cloudcmd/json , нигде не указано домена к которому должен цепляться. 

cloudcmd version current: v5.12.4
nodejs - current,last
CENTOS 6 64 , OVH vps
Chrome, last

**Comment by coderaiser** [comment]
> Загрузил 5 разных архивов с одним файлом, ниодин из них не получилось распаковать:
zip
tar
gz
7z

По-умолчанию поддерживается `.tar.gz`, его можно поменять на `.zip` в настройках (поле `packer`). Для остальных типов архивов можно использовать консоль и средства ОС.

> Когда пробовал TAR так вообще в Putty ошибка вылезла
events.js:160
throw er; // Unhandled 'error' event
^
Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
at Object.exports.decode (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/headers.js:265:40)
at Extract.onheader (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:120:39)
at Extract._write (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:243:8)
at Extract._continue (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:207:28)
at oncontinue (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:64:10)
at Extract.onheader (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:128:7)
at Extract._write (/usr/lib/node_modules/cloudcmd/node_modules/tar-stream/extract.js:243:8)
at doWrite (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/_stream_writable.js:347:64)
at writeOrBuffer (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/_stream_writable.js:336:5)
at Extract.Writable.write (/usr/lib/node_modules/cloudcmd/node_modules/readable-stream/lib/_stream_writable.js:274:11)

Ничего не могу сказать без примера файла. У меня ошибка не воспроизводится.

> Также словил баг - нажал на CONFIG кнопку внизу, и теперь вообще запустить не могу сам менеджер - пишет

[root@vps110392 json]# cloudcmd
cloudcmd --port: listen EADDRINUSE 0.0.0.0:9113

`Config` запускает окно настройки файлового менеджера, само-по-себе оно не может ничего поломать. Другое дело измененные в нем опции.

Данная ошибка говорит о том, что порт `9113` уже чем-то занят. Можно попробовать использовать другой порт, или же [завершить приложение, использующее текущий порт](https://www.cyberciti.biz/faq/what-process-has-open-linux-port/). 

> Как теперь поправить, удалить или что-то сделать - не понятно. Просмотрел все конфиги в папке /usr/lib/node_modules/cloudcmd/json , нигде не указано домена к которому должен цепляться.

Домен нигде не указывается, `Cloud Commander` не знает о том, на каком домене будет запущен, для этих целей можно использовать `nginx`. Примеры конфигов есть [на сайте](https://cloudcmd.io).

Для того, что бы указать другой порт, можно использовать параметр командной строки `--port`. Если запустить файловый менеджер таким образом:

```
cloudcmd --port 1337 --save
```

Он запустится на порту `1337`, при этом текущая настройка сохранится в поле `port` файла `~/.cloudcmd.json`.  После этого конфигурационный файл может быть изменен любым текстовым редактором.

**Comment by coderaiser** [comment]
В `Cloud Commander` [6.3.0](https://github.com/coderaiser/cloudcmd/releases/tag/v6.3.0) добавлена поддержка форматов архивов доступных для распаковки, сейчас в него входят : `tar`, `zip`, `tar.gz`, `gz`и `tgz`. Для упаковки доступны: `tar` и `zip`.
