### ISSUE TITLE
Installing on Ubuntu 17, ran into an error

### ISSUE THREAD

**Issue by guardianpwr08** [coderaiser/cloudcmd#122]
Pretty new to linux, so I'm sure the error is on my side.  Was looking to use Cloud Commander as a file browser.

I followed the instructions, installed node.js and also ran 

`sudo ln -s /usr/bin/nodejs /usr/bin/node`

to fix this error

```cloudcmd
/usr/bin/env: ‘node’: No such file or directory
```

but then I ran into this

```
$ sudo cloudcmd
/usr/local/lib/node_modules/cloudcmd/node_modules/readify/lib/readify.js:19
const good = (f) => (...a) => f(null, ...a);
                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/cloudcmd/node_modules/flop/lib/flop.js:13:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by coderaiser** [comment]
Could you please tell me what version of `node.js` are you using?
```
node -v
```

**Comment by coderaiser** [comment]
Looks like you are using `node.js` v4 which is on [maintenance mode](https://github.com/nodejs/LTS#lts-schedule1).
You can always upgrade to latest version via [nodejs.org](https://nodejs.org) or [nvm](https://github.com/creationix/nvm).

Fixed with [readify v5.0.1](https://github.com/coderaiser/readify/releases/tag/v5.0.1).
Please reinstall `Cloud Commander` with:
```
npm i cloudcmd -g
```

Is it works for you?

**Comment by guardianpwr08** [comment]
Ok progress!

I ran 
```
sudo npm install -g n
sudo n latest
sudo npm i cloudcmd -g
sudo cloudcmd
```

Then 

`sudo ufw allow 8000`

and the web portal worked!

How do I run cloudcmd as a service?

**Comment by coderaiser** [comment]
If you are using `systemd` you can create file `cloudcmd.service`:

```
[Unit]
Description=Cloud Commander

[Service]
TimeoutStartSec=0
Restart=always
User=coderaiser

WorkingDirectory=/home/coderaiser/cloudcmd

ExecStart=/home/coderaiser/.nvm/versions/node/v8.1.4/bin/node /home/coderaiser/cloudcmd/bin/cloudcmd.js

[Install]
WantedBy=multi-user.target
```

Set your `user`, path to `node` and path to `cloudcmd`:

```sh
which node
which cloudcmd
```

Then run next commands to register `systemd-service`:

```
sudo cp cloudcmd.service /etc/systemd/system/

sudo systemctl enable cloudcmd
sudo systemctl start cloudcmd
sudo systemctl status cloudcmd
```

Do not forger to set `username`, `password` and `auth` flag.

**Comment by guardianpwr08** [comment]
Ok ran into an error, likely 100% my fault :(
```

me@ubuntu:~$ sudo systemctl status cloudcmd
● cloudcmd.service - Cloud Commander
   Loaded: loaded (/etc/systemd/system/cloudcmd.service; enabled; vendor pr
   Active: failed (Result: exit-code) since Wed 2017-07-19 12:11:59 ADT; 2s
  Process: 2914 ExecStart=/home/me/.nvm/versions/node/v8.1.4/bin/node /h
 Main PID: 2914 (code=exited, status=210/CHROOT)
      CPU: 883us

Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Main process exited, c
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Unit entered failed st
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Failed with result 'ex
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Service hold-off time
Jul 19 12:11:59 ubuntu systemd[1]: Stopped Cloud Commander.
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Start request repeated
Jul 19 12:11:59 ubuntu systemd[1]: Failed to start Cloud Commander.
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Unit entered failed st
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Failed with result 'ex
lines 1-16/16 (END)...skipping...
● cloudcmd.service - Cloud Commander
   Loaded: loaded (/etc/systemd/system/cloudcmd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2017-07-19 12:11:59 ADT; 2s ago
  Process: 2914 ExecStart=/home/me/.nvm/versions/node/v8.1.4/bin/node /home/me/cloud$ (code=exit
 Main PID: 2914 (code=exited, status=210/CHROOT)
      CPU: 883us

Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Main process exited, code=exited, status=210/CHRO
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Unit entered failed state.
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Failed with result 'exit-code'.
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Service hold-off time over, scheduling restart.
Jul 19 12:11:59 ubuntu systemd[1]: Stopped Cloud Commander.
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Start request repeated too quickly.
Jul 19 12:11:59 ubuntu systemd[1]: Failed to start Cloud Commander.
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Unit entered failed state.
Jul 19 12:11:59 ubuntu systemd[1]: cloudcmd.service: Failed with result 'exit-code'.

```

**Comment by coderaiser** [comment]
You should get path of `cloudcmd` with:

```sh
which cloudcmd
```

and set to `cloudcmd.service` in `ExecStart`:

```
[Unit]
Description=Cloud Commander

[Service]
TimeoutStartSec=0
Restart=always
User=me

WorkingDirectory=/home/me

ExecStart=/usr/bin/nodejs path-of-cloudcmd/bin/cloudcmd.js

[Install]
WantedBy=multi-user.target
```

**Comment by UmamaheshwarN** [comment]
If you are trying to do this in 2021 and having issues, try to locate your `cloudcmd` install folder and use that in ExecStart path-of-cloudcmd/bin/cloudcmd.js

Also I had to change `cloudcmd.js` to `cloudcmd.mjs`
This worked for me:
`[Unit]
Description=Cloud Commander
After=network.target

[Service]
Restart=always
User=myusername
ExecStart=/home/myusername/.nvm/versions/node/v15.5.1/bin/node /home/myusername/.nvm/versions/node/v15.5.1/lib/node_modules/cloudcmd/bin/cloudcmd.mjs
WorkingDirectory=/home/myusername/.nvm/versions/node/v15.5.1/lib/node_modules/cloudcmd/

[Install]
WantedBy=multi-user.target`
