### ISSUE TITLE
autocomplete in console not work or absent

### ISSUE THREAD

**Issue by breezzz** [coderaiser/cloudcmd#140]
В консоли не работает автодополнение по табу (или его в принципе нет). 
Вставляются пробелы перед введенной командой вместо этого.
Было бы замечательно, если бы оно появилось.
Спасибо за cloudcmd!

* **Version** (`cloudcmd -v`): v8.1.3
* **Node Version** `node -v`: v9.4.0
* **OS** (`uname -a` on Linux): Linux srv.localhost.cy 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:50 UTC 2017 i686 i686 i686 GNU/Linux
* **Browser name/version**: Google Chrome 63.0.3239.132 (Официальная сборка), (64 бит)
* **Used Command Line Parameters**: -
* **Changed Config**: -

**Comment by breezzz** [comment]
Прочитал хелп нашел про терминал. Но не смог запустить

```
root@srv:/etc/systemd/system# cloudcmd --terminal --terminal-path `gritty --path` --save
cloudcmd --terminal: Cannot find module '../build/Release/pty.node'
url: http://localhost:8000/
^C
root@srv:/etc/systemd/system# npm i pty.node -g
npm ERR! code E404
npm ERR! 404 Not Found: pty.node@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/breezzz/.npm/_logs/2018-01-14T20_28_42_943Z-debug.log
root@srv:/etc/systemd/system# npm i pty -g
+ pty@0.0.0
updated 1 package in 40.751s
root@srv:/etc/systemd/system# cloudcmd --terminal --terminal-path `gritty --path` --save
cloudcmd --terminal: Cannot find module '../build/Release/pty.node'
url: http://localhost:8000/
```

**Comment by coderaiser** [comment]
> В консоли не работает автодополнение по табу (или его в принципе нет).

Его в принципе нет, но это отличная идея для улучшения [console](https://github.com/cloudcmd/console).

> Прочитал хелп нашел про терминал. Но не смог запустить

Этого должно быть достаточно:
```
npm i gritty -g
cloudcmd --terminal --terminal-path `gritty --path` --save
```

**Comment by breezzz** [comment]
> Этого должно быть достаточно:
npm i gritty -g
cloudcmd --terminal --terminal-path `gritty --path` --save

Это не сработало, поэтому попытался установить отдельно через npm, но тоже не сработало.
А если бы сработало, то это будет строка запуска ?
```
cloudcmd --terminal --terminal-path `gritty --path` --save
```
Или один раз запустить для настройки, а потом запускать просто cloudcmd?

**Comment by breezzz** [comment]
Попробовал node8 - то же самое.
Беда полностью выглядит так:
```
root@vagrant:~# npm i cloudcmd -g
/usr/bin/cloudcmd -> /usr/lib/node_modules/cloudcmd/bin/cloudcmd.js

> uws@0.14.5 install /usr/lib/node_modules/cloudcmd/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

sh: 1: cannot create build_log.txt: Permission denied
+ cloudcmd@8.1.3
added 375 packages in 35.375s
root@vagrant:~# npm i gritty -g
/usr/bin/gritty -> /usr/lib/node_modules/gritty/bin/gritty.js
/usr/bin/gritty_ -> /usr/lib/node_modules/gritty/legacy/bin/gritty.js

> uws@0.14.5 install /usr/lib/node_modules/gritty/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

sh: 1: cannot create build_log.txt: Permission denied

> node-pty@0.7.4 install /usr/lib/node_modules/gritty/node_modules/node-pty
> node scripts/install.js

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/vagrant/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/gritty/node_modules/node-pty/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/gritty/node_modules/node-pty/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/gritty/node_modules/node-pty/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/gritty/node_modules/node-pty/.node-gyp/8.9.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/gritty/node_modules/node-pty/.node-gyp"
```
дальше она уходит в цикл  пока не ctrl-C

**Comment by breezzz** [comment]
попробовал rebuild запустить вручную
```
root@vagrant:/tmp# gritty --path
/usr/lib/node_modules/gritty
root@vagrant:/tmp# node-gyp rebuild
bash: node-gyp: command not found
```
установил
`root@vagrant:/tmp# apt-get install node-gyp`

```
root@vagrant:/tmp# node-gyp rebuild
module.js:540
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```
Попробовал установить `graceful-fs`.  Не помогло. Больше пока идей нет.
```
root@vagrant:/tmp# npm i graceful-fs -g
+ graceful-fs@4.1.11
added 1 package in 0.893s
root@vagrant:/tmp# node-gyp rebuild
module.js:540
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/share/node-gyp/lib/node-gyp.js:12:10)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by coderaiser** [comment]
> Или один раз запустить для настройки, а потом запускать просто cloudcmd?
Один раз для настройки

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/vagrant/.node-gyp/8.9.4"
```

Похоже что проблема в правах доступа, я советую использовать [nvm](https://github.com/creationix/nvm) для установки `node.js`, тогда все пакеты можно будет устанавливать с помощью обычного пользователя.

Так же, `node-gyp` лучше устанавливать с помощью `npm`.

**Comment by breezzz** [comment]
да так лучше. единственно что теперь он где то глубоко стоит (/home/vagrant/.nvm/versions/node/v9.4.0/bin/cloudcmd)
и линк (sudo ln -s cloudcmd /usr/bin/cloudcmd)  не помогает
Но это уже другая проблема :)

```
# nvm install
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# node install

nvm install node
nvm use node

# cloudcmd install

npm install cloudcmd -g

# install build-essential for install gritty

sudo apt-get update
sudo apt-get install build-essential

# gritty install
npm i gritty -g

#start cloudcmd with gritty
cloudcmd --terminal --terminal-path `gritty --path` --save
```

**Comment by breezzz** [comment]
Да, автодополнение в консоли было бы замечательно, чтобы из коробки. Очень удобная вещь. Не всем нужен терминал.
