### ISSUE TITLE
8.5.0 docker crash on bulk move/copy

### ISSUE THREAD

**Issue by inamak** [coderaiser/cloudcmd#154]
Hi - I am running 8.5.0 docker installed fresh. Using latest Firefox.

Copying or moving smaller files seems ok, but if I copy a folder of video for example, it will error before finishing and the docker crashes out.

Error log:

/usr/src/app/node_modules/flop/lib/flop.js:104
flop.delete(from, callback);
^

TypeError: flop.delete is not a function
at Copymitter.flop.copy (/usr/src/app/node_modules/flop/lib/flop.js:104:24)
at emitNone (events.js:106:13)
at Copymitter.emit (events.js:208:7)
at Copymitter._cpAll (/usr/src/app/node_modules/copymitter/legacy/lib/copymitter.js:79:28)
at EventEmitter.<anonymous> (/usr/src/app/node_modules/copymitter/legacy/lib/copymitter.js:115:16)
at emitOne (events.js:116:13)
at EventEmitter.emit (events.js:211:7)
at /usr/src/app/node_modules/copymitter/legacy/lib/copymitter.js:215:21
at FSReqWrap.oncomplete (fs.js:135:15)

**Comment by coderaiser** [comment]
Thank you :), fixed with https://github.com/coderaiser/flop/commit/c4bb1c042d2d3918e7b83c88feb3f07cccf3ba26, landed in flop [v4.0.1](https://github.com/coderaiser/flop/releases/tag/v4.0.1) and updated `cloudcmd v8.5.0` on [dockerhub](https://hub.docker.com/r/coderaiser/cloudcmd/tags/).
Please pull again `coderaiser/cloudcmd:8.5.0` image.

**Comment by inamak** [comment]
Hi - On 8.5.2 and it does not crash any more. However on copy complete the blue progress icon is replaced with a red exclamation icon?
