### ISSUE TITLE
Can't copyright Big files > 2GB

### ISSUE THREAD

**Issue by kirtapix** [coderaiser/cloudcmd#163]
* **Version** (`cloudcmd -v`): 9.1.1
* **Node Version** `node -v`: 8.11.1
* **OS** (`uname -a` on Linux): raspian stretch up-to-date
* **Browser name/version**: latestn firefox
* **Used Command Line Parameters**: 
* **Changed Config**: 

Hi,
When I copy a big file, file disappear at the end. I can see disk usage dicreasing while file is copying. Tried with cloudcmd launched by root and regular user. File copy under 2GB is ok.

Thanks in advance !

**Comment by coderaiser** [comment]
I can not reproduce such behavior with `3GB` files.
Could you please try to use `console` or `terminal` for this purpose. Is it works?

**Comment by coderaiser** [comment]
There is such a thing like [shinju](https://github.com/cloudcmd/shinju) but it wasn't updated for a long time. It is a cli tool for [console-io](https://github.com/cloudcmd/console-io). It should work with `cloudcmd` as well. But wasn't updated for a long time, and need to be actualized. It uses `socket.io-client` to for connection and protocol [is not hard](https://github.com/cloudcmd/console-io/blob/master/server/index.js#L141).

What do you mean by copying a file? Command line like `ssh`?

**Comment by kirtapix** [comment]
In fact I want to understand why I can't copy files with size >2gb. I as wondering if I could reproduce in command line what is done in cloudcmd when I copy/paste a file

**Comment by coderaiser** [comment]
Try to use node `v10` for this purpose. Could you please reinstall `cloudcmd` modules used for copying has been changed drastically.

**Comment by coderaiser** [comment]
Could you please try to update node to `>=v8.5` or `v10` and try to use [fs.copyFileSync](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_copyfilesync_src_dest_flags):

```sh
$ node -e "fs.copyFileSync('./big-file-path', './big-file-copy-path');"
```

And show me the output.

**Comment by kirtapix** [comment]
Here is the output :

```
node -e "fs.copyFileSync('/media/grandDur/download/film/Back.to.the.Future.Part.III.720p.mkv', '/media/grandDur/Fi
lms/Back.to.the.Future.Part.III.720p.mkv');"                                                                                   
fs.js:1918                                                                                                                     
  binding.copyFile(src, dest, flags);                                                                                          
          ^                                                                                                                    
                                                                                                                               
Error: Unknown system error -181063143: Unknown system error -181063143, copyfile '/media/grandDur/download/film/Back.to.the.Fu
ture.Part.III.720p.mkv' -> '/media/grandDur/Films/Back.to.the.Future.Part.III.720p.mkv'                                        
    at Object.fs.copyFileSync (fs.js:1918:11)                                                                                  
    at [eval]:1:4                                                                                                              
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)                                                                  
    at Object.runInThisContext (vm.js:139:38)                                                                                  
    at Object.<anonymous> ([eval]-wrapper:6:22)                                                                                
    at Module._compile (module.js:652:30)                                                                                      
    at evalScript (bootstrap_node.js:463:27)                                                                                   
    at startup (bootstrap_node.js:164:9)                                                                                       
    at bootstrap_node.js:609:3                                                                                                 
```

**Comment by coderaiser** [comment]
Looks like a bug of `node.js`  What version have you used? I think you should create an issue in [node.js repo](https://github.com/nodejs/node/issues).

**Comment by coderaiser** [comment]
I'm using `node v10` and `node v8.11.1` and can not reproduce such behaviour on `Windows`, `Linux` and `Mac Os`. But I have no `rapspbary pi` devices.

**Comment by mklnz** [comment]
> * **Version** (`cloudcmd -v`): 9.1.1
> * **Node Version** `node -v`: 8.11.1
> * **OS** (`uname -a` on Linux): raspian stretch up-to-date
> * **Browser name/version**: latestn firefox
> * **Used Command Line Parameters**:
> * **Changed Config**:
> 
> Hi,
> When I copy a big file, file disappear at the end. I can see disk usage dicreasing while file is copying. Tried with cloudcmd launched by root and regular user. File copy under 2GB is ok.
> 
> Thanks in advance !

Sorry to post on a kinda non cloudcmd issue, but I have the same problem with Node not able to copy files over 2GB, I tried with a 1.999GB file and it worked just fine. I've looked all over the internet and this is the only place where someone has the same symptoms as me. Did you manage to fix it in the end?

https://stackoverflow.com/questions/58500025/node-unknown-system-error-when-copying-large-files-over-2gb

**Comment by kirtapix** [comment]
> 
> 
> > * **Version** (`cloudcmd -v`): 9.1.1
> > * **Node Version** `node -v`: 8.11.1
> > * **OS** (`uname -a` on Linux): raspian stretch up-to-date
> > * **Browser name/version**: latestn firefox
> > * **Used Command Line Parameters**:
> > * **Changed Config**:
> > 
> > Hi,
> > When I copy a big file, file disappear at the end. I can see disk usage dicreasing while file is copying. Tried with cloudcmd launched by root and regular user. File copy under 2GB is ok.
> > Thanks in advance !
> 
> Sorry to post on a kinda non cloudcmd issue, but I have the same problem with Node not able to copy files over 2GB, I tried with a 1.999GB file and it worked just fine. I've looked all over the internet and this is the only place where someone has the same symptoms as me. Did you manage to fix it in the end?
> 
> https://stackoverflow.com/questions/58500025/node-unknown-system-error-when-copying-large-files-over-2gb

Hi mklnz,

I manage to get it working by updating node to v10.
