### ISSUE TITLE
Error at service starting

### ISSUE THREAD

**Issue by epichat13** [coderaiser/cloudcmd#176]
* **Version** (cloudcmd -v) : 
Command failed, i installed the last one with npm
* **Node Version** : 
v5.12.0
* **OS** : 
Linux server 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* **Used Command Line Parameters**: 
cloudcmd and cloudcmd -v

Hi, i installed nodejs and cloud commander, and the installation finished without erros.
But at the time of first start i get the following error:

/usr/lib/node_modules/cloudcmd/node_modules/pullout/lib/pullout.js:3
module.exports = (stream, type, fn = type) => {
                                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/cloudcmd/server/config.js:18:27)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

I did not modified anything and i tried to reinstall but it's not working. Thanks in advance.

**Comment by coderaiser** [comment]
Please try to update `node` to `v8` or `v10`, `v5` is not supported anymore.
Could you please tell me what version of `cloudcmd` are you using?

**Comment by coderaiser** [comment]
Thank you, fixed with https://github.com/coderaiser/pullout/commit/f07d09b1a0048eb95b19ea0db4afb7189e184fe2, landed in [pullout@v1.0.3](https://github.com/coderaiser/pullout/releases/tag/v1.0.3).

Please reinstall `cloudcmd`.
