### ISSUE TITLE
cloudcmd unexpected token with nodejs v6.14.3

### ISSUE THREAD

**Issue by chrisdotcollins** [coderaiser/cloudcmd#206]
* **Version** (`cloudcmd -v`): cloudcmd@11.8.2
* **Node Version** `node -v`: v6.14.3
* **OS** (`uname -a` on Linux): CentOS Linux release 7.5.1804 (Core)
* **Browser name/version**: Chrome v69.0.3497.100
* **Used Command Line Parameters**: None
* **Changed Config**: None

cloudcmd is failing to start at all, straight from a basic install. This has occurred on a couple of similar systems (these are Virtualbox Centos VMs)

$ npm i cloudcmd -g
<snip, though seems to complete ok>
$ cloudcmd
/usr/lib/node_modules/cloudcmd/server/config.js:55
    ...rootConfig,
    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/cloudcmd/bin/cloudcmd.js:12:16)

Any ideas?

Thanks,

Chris

**Comment by coderaiser** [comment]
The thing is `node version < 8` is not supported since [Cloud Commander v11.0.0](https://github.com/coderaiser/cloudcmd/releases/tag/v11.0.0) major release.

Please upgrade to `v10`, which is [LTS](https://github.com/nodejs/Release#release-schedule), or at least to `v8`, `v6` will be deprecated in April.

Is it works for you?

**Comment by coderaiser** [comment]
That's OK :), glad to help.
