### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by brahmastra** [coderaiser/cloudcmd#23]
Not working on Ubuntu 14.04
$  cloudcmd -v
$
$ cloudcmd -h
$ 
On localhost:8000 nothing

**Comment by eGGshke** [comment]
```
> dword@1.3.11 postinstall /usr/local/lib/node_modules/cloudcmd/node_modules/dword
> bower install

/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:56
				throw err;
				      ^
Error: EACCES, permission denied '/home/egg/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:502:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:354:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:460:26)
 
> ws@0.5.0 install /usr/local/lib/node_modules/cloudcmd/node_modules/socket.io/node_modules/engine.io/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Вход в каталог `/usr/local/lib/node_modules/cloudcmd/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Выход из каталога `/usr/local/lib/node_modules/cloudcmd/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'

> edward@1.4.8 postinstall /usr/local/lib/node_modules/cloudcmd/node_modules/edward
> bower install

/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:56
				throw err;
				      ^
Error: EACCES, permission denied '/home/egg/.config/configstore/insight-bower.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:502:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:354:15)
    at Object.create.all.get (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/bower/node_modules/insight/lib/index.js:26:34)
    at ensureInsight (/usr/local/lib/node_modules/bower/lib/util/analytics.js:26:19)
    at Object.setup (/usr/local/lib/node_modules/bower/lib/util/analytics.js:43:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/bower/bin/bower:72:11)
    at Module._compile (module.js:460:26)

> ws@0.4.31 install /usr/local/lib/node_modules/cloudcmd/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Вход в каталог `/usr/local/lib/node_modules/cloudcmd/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Выход из каталога `/usr/local/lib/node_modules/cloudcmd/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/build'
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "cloudcmd" "-g"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! dword@1.3.11 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dword@1.3.11 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the dword package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls dword
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/egg/npm-debug.log
```

**Comment by coderaiser** [comment]
@eGGshke try to change permissions to file `/home/egg/.config/configstore/insight-bower.yml`. Or remove it. This is error message:
```js
./usr/local/lib/node_modules/bower/node_modules/insight/node_modules/configstore/index.js:56
                throw err;
                      ^
Error: EACCES, permission denied '/home/egg/.config/configstore/insight-bower.yml'
You don't have access to this file.
```
There is such [issue](https://github.com/bower/bower/issues/1607) in bower repo.
You coud try to remove global bower. And install iojs via [nvm](https://github.com/creationix/nvm). And than install bower and Cloud Commander globally again. Sudo not required for this.

**Comment by coderaiser** [comment]
@eGGshke did it help you?

**Comment by eGGshke** [comment]
@coderaiser Yeah, nvm solved my problem. Thank you !

**Comment by coderaiser** [comment]
That's great :).
