### ISSUE TITLE
Cloudcommander crashes on "Edit"

### ISSUE THREAD

**Issue by hanspalsson** [coderaiser/cloudcmd#277]
* **Version** (`cloudcmd -v`): 14.3.4
* **Node Version** `node -v`: 12.14.1
* **OS** (`uname -a` on Linux): Debian 9 4.9.189-3+deb9u2
* **Browser name/version**: Chrome
* **Used Command Line Parameters**: sudo cloudcmd 
* **Changed Config**: 

Starting cloudcmd with _sudo cloudcmd_ is ok, and browsing works fine. But when I try to edit a file Cloudcommander crashes with the following info;

`ENOENT: no such file or directory, open '/root/.edward.json' Promise {
  <rejected> [Error: ENOENT: no such file or directory, open '/root/.edward.json'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '/root/.edward.json'
  }
}`

Swithing to another editor gives the same result. It has worked without problems until now.

**Comment by coderaiser** [comment]
Thank you, fixed with https://github.com/cloudcmd/dword/commit/b2404c99d4e2d68e9509fdbb498b808e0bb63684, https://github.com/cloudcmd/edward/commit/b9deca86653f90188b05d018b6ec1ade5c7b99c9. Please reinstall Cloud Commander. Is it helped?

**Comment by hanspalsson** [comment]
Hi! Thanks, but unfortunatly no, however now with a new error message.
`tryToCatch is not a function or its return value is not iterable Promise {
  <rejected> TypeError: tryToCatch is not a function or its return value is not iterable
      at module.exports (/usr/lib/node_modules/cloudcmd/node_modules/edward/server/edit.js:13:27)
      at Layer.handle [as handle_request] (/usr/lib/node_modules/cloudcmd/node_modules/edward/node_modules/router/lib/layer.js:93:5)
      at next (/usr/lib/node_modules/cloudcmd/node_modules/edward/node_modules/router/lib/route.js:144:13)
      at configFn (/usr/lib/node_modules/cloudcmd/node_modules/edward/server/index.js:105:16)
      at currify (/usr/lib/node_modules/cloudcmd/node_modules/currify/lib/currify.js:16:16)
      at again (/usr/lib/node_modules/cloudcmd/node_modules/currify/lib/currify.js:19:16)
      at /usr/lib/node_modules/cloudcmd/node_modules/currify/lib/currify.js:7:32
      at Layer.handle [as handle_request] (/usr/lib/node_modules/cloudcmd/node_modules/edward/node_modules/router/lib/layer.js:93:5)
      at next (/usr/lib/node_modules/cloudcmd/node_modules/edward/node_modules/router/lib/route.js:144:13)
      at edward (/usr/lib/node_modules/cloudcmd/node_modules/edward/server/index.js:96:5)
}`

**Comment by coderaiser** [comment]
Fixed with https://github.com/cloudcmd/edward/commit/f7edc54f775b1a5dbdf2508a73da16bf38e3c6fe, please try again :)

**Comment by hanspalsson** [comment]
It works! Excellent work, thank you!
