### ISSUE TITLE
Cloudcmd wont start

### ISSUE THREAD

**Issue by Sub-7** [coderaiser/cloudcmd#338]
Cloudcmd wont start.
what's wrong here?

Version : v15.9.3
Node Version : v14.16.0
OS : Ubuntu 20.04 Proxmox LXC 

`root@HMS:~# node -v
v14.16.0
root@HMS:~# npm -v
6.14.11
root@HMS:~# cloudcmd
url: http://localhost:8000/
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:8000/' ]
}`

**Comment by Sub-7** [comment]
apt install xdg-utils , solved problem

**Comment by coderaiser** [comment]
`cloudcmd --no-open --save` also will.
