### ISSUE TITLE
v 3.2.0

### ISSUE THREAD

**Issue by wormen** [coderaiser/cloudcmd#37]
эта версия ФМ не обновляется и не устанавливается на nodejs 0.12.4

```
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "cloudcmd" "-g"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
npm ERR! code EISGIT

npm ERR! git Appears to be a git repo or submodule.
npm ERR! git     C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by coderaiser** [comment]
Похоже, что установленную глобально версию, npm считает git репозиторием.
Попробуйте:
```
npm remove cloudcmd -g
npm install cloudcmd -g
```
Если не выйдет, попробуйте самостоятельно удалить папку `  C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd`.

Если и это не поможет попробуйте [iojs](https://iojs.org).

**Comment by wormen** [comment]
пробовал по всякому, ошибка одинаковая
iojs не вижу смысла ставить, он более не развивается, команда давно уже объединилась снова

**Comment by coderaiser** [comment]
Как это не развивается? Сегодня вышла версия [2.3.0](https://github.com/nodejs/io.js/blob/master/CHANGELOG.md#2015-06-13-version-230-rvagg). Если ничего не помогает (даже удаление вручную) советую попробовать iojs либо обновить npm:
```
npm i npm -g
```
Другие приложения получается глобально установить с помощью npm?

**Comment by coderaiser** [comment]
Проблема еще не решилась? У меня на `Win8` все нормально устанавливается с node `v0.12.4`.

**Comment by wormen** [comment]
нет, не решались, у меня так же win8, но x64 enterprise

**Comment by coderaiser** [comment]
Что вы пробовали из описанного выше?

**Comment by wormen** [comment]
пробовал сначала
npm update cloudcmd -g

потом
npm remove cloudcmd -g

а потом уже все вручную зачистил ....

по прежнему ошибка, которая в первом посте

**Comment by coderaiser** [comment]
Другие модули глобально устанавливаютсям нормально? Вы можете всю ошибку показать?

**Comment by wormen** [comment]
да, с другими нормально все, проблема только с этим
-----
вот весь лог, который относится только к этому модулю

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'cloudcmd',
1 verbose cli   '-g' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of C:\Users\Администратор\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Администратор\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cloudcmd', null ]
7 verbose cache add spec cloudcmd
8 silly cache add parsed spec { raw: 'cloudcmd',
8 silly cache add   scope: null,
8 silly cache add   name: 'cloudcmd',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cloudcmd@*
10 verbose addNamed "*" is a valid semver range for cloudcmd
11 silly addNameRange { name: 'cloudcmd', range: '*', hasData: false }
12 silly mapToRegistry name cloudcmd
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/cloudcmd
16 verbose addNameRange registry:https://registry.npmjs.org/cloudcmd not in flight; fetching
17 verbose request uri https://registry.npmjs.org/cloudcmd
18 verbose request no auth needed
19 info attempt registry request try #1 at 16:54:50
20 verbose request id 43227731d3dd1a11
21 verbose etag "7UG8HNWOAJWD2FUXYXRPQK90C"
22 http request GET https://registry.npmjs.org/cloudcmd
23 http 304 https://registry.npmjs.org/cloudcmd
24 silly get cb [ 304,
24 silly get   { date: 'Mon, 15 Jun 2015 07:55:55 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     'cache-control': 'max-age=60',
24 silly get     etag: '"7UG8HNWOAJWD2FUXYXRPQK90C"',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-ams4140-AMS',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1434354955.644631,VS0,VE1153',
24 silly get     vary: 'Accept' } ]
25 verbose etag https://registry.npmjs.org/cloudcmd from cache
26 verbose get saving cloudcmd to C:\Users\Администратор\AppData\Roaming\npm-cache\registry.npmjs.org\cloudcmd\.cache.json
27 silly addNameRange number 2 { name: 'cloudcmd', range: '*', hasData: true }
28 silly addNameRange versions [ 'cloudcmd',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.8.1',
28 silly addNameRange     '0.8.2',
28 silly addNameRange     '0.8.3',
28 silly addNameRange     '0.8.4',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.0.1',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.3.0',
28 silly addNameRange     '1.3.1',
28 silly addNameRange     '1.3.2',
28 silly addNameRange     '1.4.0',
28 silly addNameRange     '1.4.1',
28 silly addNameRange     '1.5.0',
28 silly addNameRange     '1.5.1',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.1.0',
28 silly addNameRange     '2.2.0',
28 silly addNameRange     '2.2.1',
28 silly addNameRange     '2.3.0',
28 silly addNameRange     '2.3.1',
28 silly addNameRange     '2.4.0',
28 silly addNameRange     '2.4.1',
28 silly addNameRange     '2.4.2',
28 silly addNameRange     '2.5.0',
28 silly addNameRange     '2.5.1',
28 silly addNameRange     '2.6.0',
28 silly addNameRange     '2.7.0',
28 silly addNameRange     '2.7.1',
28 silly addNameRange     '2.8.0',
28 silly addNameRange     '2.9.0',
28 silly addNameRange     '2.9.1',
28 silly addNameRange     '2.9.2',
28 silly addNameRange     '2.9.3',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.0.1',
28 silly addNameRange     '3.0.2',
28 silly addNameRange     '3.0.3',
28 silly addNameRange     '3.0.4',
28 silly addNameRange     '3.1.0',
28 silly addNameRange     '3.1.1',
28 silly addNameRange     '3.1.2',
28 silly addNameRange     '3.1.3',
28 silly addNameRange     '3.1.4',
28 silly addNameRange     '3.2.0' ] ]
29 silly addNamed cloudcmd@3.2.0
30 verbose addNamed "3.2.0" is a plain semver version for cloudcmd
31 silly cache afterAdd cloudcmd@3.2.0
32 verbose afterAdd C:\Users\Администратор\AppData\Roaming\npm-cache\cloudcmd\3.2.0\package\package.json not in flight; writing
33 verbose afterAdd C:\Users\Администратор\AppData\Roaming\npm-cache\cloudcmd\3.2.0\package\package.json written
34 silly install resolved [ { name: 'cloudcmd',
34 silly install resolved     version: '3.2.0',
34 silly install resolved     author:
34 silly install resolved      { name: 'coderaiser',
34 silly install resolved        email: 'mnemonic.enemy@gmail.com',
34 silly install resolved        url: 'https://github.com/coderaiser' },
34 silly install resolved     description: 'Cloud Commander orthodox web file manager with console and editor',
34 silly install resolved     homepage: 'http://cloudcmd.io',
34 silly install resolved     repository: { type: 'git', url: 'git://github.com/coderaiser/cloudcmd.git' },
34 silly install resolved     keywords:
34 silly install resolved      [ 'file manager',
34 silly install resolved        'orthodox',
34 silly install resolved        'file',
34 silly install resolved        'folder',
34 silly install resolved        'console',
34 silly install resolved        'editor' ],
34 silly install resolved     bin: { cloudcmd: 'bin/cloudcmd.js', iocmd: 'bin/iocmd.js' },
34 silly install resolved     scripts:
34 silly install resolved      { test: 'gulp default',
34 silly install resolved        start: 'node bin/cloudcmd.js',
34 silly install resolved        gulp: 'gulp',
34 silly install resolved        yaspeller: 'yaspeller .',
34 silly install resolved        wisdom: 'gulp release',
34 silly install resolved        bower: 'bower' },
34 silly install resolved     directories: { man: 'man' },
34 silly install resolved     subdomain: 'cloudcmd',
34 silly install resolved     dependencies:
34 silly install resolved      { checkup: '~1.3.0',
34 silly install resolved        'console-io': '~2.2.0',
34 silly install resolved        copymitter: '~1.8.0',
34 silly install resolved        dword: '~1.5.0',
34 silly install resolved        edward: '~1.6.0',
34 silly install resolved        execon: '~1.2.0',
34 silly install resolved        express: '~4.12.0',
34 silly install resolved        faust: '~1.0.0',
34 silly install resolved        'files-io': '~1.2.0',
34 silly install resolved        flop: '~1.1.0',
34 silly install resolved        'format-io': '~0.9.6',
34 silly install resolved        'http-auth': '~2.2.3',
34 silly install resolved        jag: '~1.0.0',
34 silly install resolved        'join-io': '~1.4.0',
34 silly install resolved        jonny: '~1.0.0',
34 silly install resolved        'markdown-it': '~4.2.0',
34 silly install resolved        mellow: '~1.3.0',
34 silly install resolved        minify: '~1.4.0',
34 silly install resolved        minimist: '~1.1.0',
34 silly install resolved        mollify: '~1.0.0',
34 silly install resolved        'pipe-io': '~1.1.1',
34 silly install resolved        ponse: '~1.4.0',
34 silly install resolved        rendy: '~1.1.0',
34 silly install resolved        restafary: '~1.3.0',
34 silly install resolved        'socket.io': '~1.3.5',
34 silly install resolved        spero: '~1.0.0',
34 silly install resolved        'try-catch': '~1.0.0',
34 silly install resolved        tryrequire: '~1.1.5' },
34 silly install resolved     devDependencies:
34 silly install resolved      { bower: '~1.4.1',
34 silly install resolved        gulp: '^3.9.0',
34 silly install resolved        'gulp-jscs': '~1.6.0',
34 silly install resolved        'gulp-jshint': '^1.11.0',
34 silly install resolved        'gulp-mocha': '~2.1.0',
34 silly install resolved        'gulp-recess': '~1.1.1',
34 silly install resolved        minor: '~1.2.2',
34 silly install resolved        morgan: '~1.5.0',
34 silly install resolved        place: '~1.1.2',
34 silly install resolved        shortdate: '~1.0.1',
34 silly install resolved        should: '~6.0.1',
34 silly install resolved        yaspeller: '~2.4.0' },
34 silly install resolved     engines: { node: '>=0.10' },
34 silly install resolved     license: 'MIT',
34 silly install resolved     main: 'lib/cloudcmd.js',
34 silly install resolved     man: [ '/home/coderaiser/cloudcmd/man/cloudcmd.1' ],
34 silly install resolved     gitHead: '896f9347a1069fb2952fc3ee617656296b5f314e',
34 silly install resolved     bugs: { url: 'https://github.com/coderaiser/cloudcmd/issues' },
34 silly install resolved     _id: 'cloudcmd@3.2.0',
34 silly install resolved     _shasum: 'd875613709a5c580e18c861eb9f800aed49a71d6',
34 silly install resolved     _from: 'cloudcmd@*',
34 silly install resolved     _npmVersion: '2.11.0',
34 silly install resolved     _nodeVersion: '2.2.1',
34 silly install resolved     _npmUser: { name: 'coderaiser', email: 'mnemonic.enemy@gmail.com' },
34 silly install resolved     maintainers: [ [Object] ],
34 silly install resolved     dist:
34 silly install resolved      { shasum: 'd875613709a5c580e18c861eb9f800aed49a71d6',
34 silly install resolved        tarball: 'http://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz' },
34 silly install resolved     _resolved: 'https://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz',
34 silly install resolved     readme: 'ERROR: No README data found!' } ]
35 info install cloudcmd@3.2.0 into C:\Users\Администратор\AppData\Roaming\npm
36 info installOne cloudcmd@3.2.0
37 verbose installOne of cloudcmd to C:\Users\Администратор\AppData\Roaming\npm not in flight; installing
38 verbose lock using C:\Users\Администратор\AppData\Roaming\npm-cache\_locks\cloudcmd-17c66b7dd85dea10.lock for C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
39 verbose unlock done using C:\Users\Администратор\AppData\Roaming\npm-cache\_locks\cloudcmd-17c66b7dd85dea10.lock for C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
40 verbose stack Error: Appears to be a git repo or submodule.
40 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:139:15
40 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
41 verbose cwd C:\Users\Администратор
42 error Windows_NT 6.2.9200
43 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "cloudcmd" "-g"
44 error node v0.12.4
45 error npm  v2.10.1
46 error path C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
47 error code EISGIT
48 error git Appears to be a git repo or submodule.
48 error git     C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
48 error git Refusing to remove it. Update manually,
48 error git or move it out of the way first.
49 verbose exit [ 1, true ]
```

**Comment by coderaiser** [comment]
Попробуйте
```
npm cache clean
```

Если не поможет
```
npm i npm -g

**Comment by wormen** [comment]
почистил каталог npm-cache что не удалилось командой, удалил вручную ....
там кстати бы каталог не .git а __git_registry ... сути это конечно мало меняет ... для меня так же загадка, как он там появился ...

в общем, теперь немного другая ошибка

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'i',
1 verbose cli   'cloudcmd',
1 verbose cli   '-g' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of C:\Users\Администратор\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\Администратор\AppData\Roaming\npm\package.json
6 silly cache add args [ 'cloudcmd', null ]
7 verbose cache add spec cloudcmd
8 silly cache add parsed spec { raw: 'cloudcmd',
8 silly cache add   scope: null,
8 silly cache add   name: 'cloudcmd',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '*',
8 silly cache add   type: 'range' }
9 silly addNamed cloudcmd@*
10 verbose addNamed "*" is a valid semver range for cloudcmd
11 silly addNameRange { name: 'cloudcmd', range: '*', hasData: false }
12 silly mapToRegistry name cloudcmd
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/cloudcmd
16 verbose addNameRange registry:https://registry.npmjs.org/cloudcmd not in flight; fetching
17 verbose request uri https://registry.npmjs.org/cloudcmd
18 verbose request no auth needed
19 info attempt registry request try #1 at 19:48:14
20 verbose request id 9212f2fd3febaf1a
21 http request GET https://registry.npmjs.org/cloudcmd
22 http 200 https://registry.npmjs.org/cloudcmd
23 silly get cb [ 200,
23 silly get   { server: 'CouchDB/1.5.0 (Erlang OTP/R16B03)',
23 silly get     etag: '"7UG8HNWOAJWD2FUXYXRPQK90C"',
23 silly get     'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=60',
23 silly get     'content-length': '109285',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Mon, 15 Jun 2015 10:49:19 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-fra1226-FRA',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1434365359.811768,VS0,VE184',
23 silly get     vary: 'Accept' } ]
24 verbose get saving cloudcmd to C:\Users\Администратор\AppData\Roaming\npm-cache\registry.npmjs.org\cloudcmd\.cache.json
25 verbose getCacheStat cache creation not in flight; initializing
26 verbose makeCacheDir UID & GID are irrelevant on win32
27 silly addNameRange number 2 { name: 'cloudcmd', range: '*', hasData: true }
28 silly addNameRange versions [ 'cloudcmd',
28 silly addNameRange   [ '0.1.0',
28 silly addNameRange     '0.1.1',
28 silly addNameRange     '0.1.2',
28 silly addNameRange     '0.1.3',
28 silly addNameRange     '0.1.4',
28 silly addNameRange     '0.1.5',
28 silly addNameRange     '0.1.6',
28 silly addNameRange     '0.1.7',
28 silly addNameRange     '0.1.8',
28 silly addNameRange     '0.1.9',
28 silly addNameRange     '0.2.0',
28 silly addNameRange     '0.3.0',
28 silly addNameRange     '0.4.0',
28 silly addNameRange     '0.5.0',
28 silly addNameRange     '0.6.0',
28 silly addNameRange     '0.7.0',
28 silly addNameRange     '0.8.0',
28 silly addNameRange     '0.8.1',
28 silly addNameRange     '0.8.2',
28 silly addNameRange     '0.8.3',
28 silly addNameRange     '0.8.4',
28 silly addNameRange     '0.9.0',
28 silly addNameRange     '0.9.1',
28 silly addNameRange     '0.9.2',
28 silly addNameRange     '1.0.0',
28 silly addNameRange     '1.0.1',
28 silly addNameRange     '1.1.0',
28 silly addNameRange     '1.1.1',
28 silly addNameRange     '1.2.0',
28 silly addNameRange     '1.3.0',
28 silly addNameRange     '1.3.1',
28 silly addNameRange     '1.3.2',
28 silly addNameRange     '1.4.0',
28 silly addNameRange     '1.4.1',
28 silly addNameRange     '1.5.0',
28 silly addNameRange     '1.5.1',
28 silly addNameRange     '2.0.0',
28 silly addNameRange     '2.1.0',
28 silly addNameRange     '2.2.0',
28 silly addNameRange     '2.2.1',
28 silly addNameRange     '2.3.0',
28 silly addNameRange     '2.3.1',
28 silly addNameRange     '2.4.0',
28 silly addNameRange     '2.4.1',
28 silly addNameRange     '2.4.2',
28 silly addNameRange     '2.5.0',
28 silly addNameRange     '2.5.1',
28 silly addNameRange     '2.6.0',
28 silly addNameRange     '2.7.0',
28 silly addNameRange     '2.7.1',
28 silly addNameRange     '2.8.0',
28 silly addNameRange     '2.9.0',
28 silly addNameRange     '2.9.1',
28 silly addNameRange     '2.9.2',
28 silly addNameRange     '2.9.3',
28 silly addNameRange     '3.0.0',
28 silly addNameRange     '3.0.1',
28 silly addNameRange     '3.0.2',
28 silly addNameRange     '3.0.3',
28 silly addNameRange     '3.0.4',
28 silly addNameRange     '3.1.0',
28 silly addNameRange     '3.1.1',
28 silly addNameRange     '3.1.2',
28 silly addNameRange     '3.1.3',
28 silly addNameRange     '3.1.4',
28 silly addNameRange     '3.2.0' ] ]
29 silly addNamed cloudcmd@3.2.0
30 verbose addNamed "3.2.0" is a plain semver version for cloudcmd
31 silly mapToRegistry name cloudcmd
32 silly mapToRegistry using default registry
33 silly mapToRegistry registry https://registry.npmjs.org/
34 silly mapToRegistry uri https://registry.npmjs.org/cloudcmd
35 verbose addRemoteTarball https://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz not in flight; adding
36 verbose addRemoteTarball [ 'https://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz',
36 verbose addRemoteTarball   'd875613709a5c580e18c861eb9f800aed49a71d6' ]
37 info retry fetch attempt 1 at 19:48:16
38 info attempt registry request try #1 at 19:48:16
39 http fetch GET https://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz
40 http fetch 200 https://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz
41 silly fetchAndShaCheck shasum d875613709a5c580e18c861eb9f800aed49a71d6
42 verbose addTmpTarball c:\TEMP\npm-6104-11a4667c\registry.npmjs.org\cloudcmd\-\cloudcmd-3.2.0.tgz not in flight; adding
43 verbose addTmpTarball already have metadata; skipping unpack for cloudcmd@3.2.0
44 silly cache afterAdd cloudcmd@3.2.0
45 verbose afterAdd C:\Users\Администратор\AppData\Roaming\npm-cache\cloudcmd\3.2.0\package\package.json not in flight; writing
46 verbose afterAdd C:\Users\Администратор\AppData\Roaming\npm-cache\cloudcmd\3.2.0\package\package.json written
47 silly install resolved [ { name: 'cloudcmd',
47 silly install resolved     version: '3.2.0',
47 silly install resolved     author:
47 silly install resolved      { name: 'coderaiser',
47 silly install resolved        email: 'mnemonic.enemy@gmail.com',
47 silly install resolved        url: 'https://github.com/coderaiser' },
47 silly install resolved     description: 'Cloud Commander orthodox web file manager with console and editor',
47 silly install resolved     homepage: 'http://cloudcmd.io',
47 silly install resolved     repository: { type: 'git', url: 'git://github.com/coderaiser/cloudcmd.git' },
47 silly install resolved     keywords:
47 silly install resolved      [ 'file manager',
47 silly install resolved        'orthodox',
47 silly install resolved        'file',
47 silly install resolved        'folder',
47 silly install resolved        'console',
47 silly install resolved        'editor' ],
47 silly install resolved     bin: { cloudcmd: 'bin/cloudcmd.js', iocmd: 'bin/iocmd.js' },
47 silly install resolved     scripts:
47 silly install resolved      { test: 'gulp default',
47 silly install resolved        start: 'node bin/cloudcmd.js',
47 silly install resolved        gulp: 'gulp',
47 silly install resolved        yaspeller: 'yaspeller .',
47 silly install resolved        wisdom: 'gulp release',
47 silly install resolved        bower: 'bower' },
47 silly install resolved     directories: { man: 'man' },
47 silly install resolved     subdomain: 'cloudcmd',
47 silly install resolved     dependencies:
47 silly install resolved      { checkup: '~1.3.0',
47 silly install resolved        'console-io': '~2.2.0',
47 silly install resolved        copymitter: '~1.8.0',
47 silly install resolved        dword: '~1.5.0',
47 silly install resolved        edward: '~1.6.0',
47 silly install resolved        execon: '~1.2.0',
47 silly install resolved        express: '~4.12.0',
47 silly install resolved        faust: '~1.0.0',
47 silly install resolved        'files-io': '~1.2.0',
47 silly install resolved        flop: '~1.1.0',
47 silly install resolved        'format-io': '~0.9.6',
47 silly install resolved        'http-auth': '~2.2.3',
47 silly install resolved        jag: '~1.0.0',
47 silly install resolved        'join-io': '~1.4.0',
47 silly install resolved        jonny: '~1.0.0',
47 silly install resolved        'markdown-it': '~4.2.0',
47 silly install resolved        mellow: '~1.3.0',
47 silly install resolved        minify: '~1.4.0',
47 silly install resolved        minimist: '~1.1.0',
47 silly install resolved        mollify: '~1.0.0',
47 silly install resolved        'pipe-io': '~1.1.1',
47 silly install resolved        ponse: '~1.4.0',
47 silly install resolved        rendy: '~1.1.0',
47 silly install resolved        restafary: '~1.3.0',
47 silly install resolved        'socket.io': '~1.3.5',
47 silly install resolved        spero: '~1.0.0',
47 silly install resolved        'try-catch': '~1.0.0',
47 silly install resolved        tryrequire: '~1.1.5' },
47 silly install resolved     devDependencies:
47 silly install resolved      { bower: '~1.4.1',
47 silly install resolved        gulp: '^3.9.0',
47 silly install resolved        'gulp-jscs': '~1.6.0',
47 silly install resolved        'gulp-jshint': '^1.11.0',
47 silly install resolved        'gulp-mocha': '~2.1.0',
47 silly install resolved        'gulp-recess': '~1.1.1',
47 silly install resolved        minor: '~1.2.2',
47 silly install resolved        morgan: '~1.5.0',
47 silly install resolved        place: '~1.1.2',
47 silly install resolved        shortdate: '~1.0.1',
47 silly install resolved        should: '~6.0.1',
47 silly install resolved        yaspeller: '~2.4.0' },
47 silly install resolved     engines: { node: '>=0.10' },
47 silly install resolved     license: 'MIT',
47 silly install resolved     main: 'lib/cloudcmd.js',
47 silly install resolved     man: [ '/home/coderaiser/cloudcmd/man/cloudcmd.1' ],
47 silly install resolved     gitHead: '896f9347a1069fb2952fc3ee617656296b5f314e',
47 silly install resolved     bugs: { url: 'https://github.com/coderaiser/cloudcmd/issues' },
47 silly install resolved     _id: 'cloudcmd@3.2.0',
47 silly install resolved     _shasum: 'd875613709a5c580e18c861eb9f800aed49a71d6',
47 silly install resolved     _from: 'cloudcmd@*',
47 silly install resolved     _npmVersion: '2.11.0',
47 silly install resolved     _nodeVersion: '2.2.1',
47 silly install resolved     _npmUser: { name: 'coderaiser', email: 'mnemonic.enemy@gmail.com' },
47 silly install resolved     maintainers: [ [Object] ],
47 silly install resolved     dist:
47 silly install resolved      { shasum: 'd875613709a5c580e18c861eb9f800aed49a71d6',
47 silly install resolved        tarball: 'http://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz' },
47 silly install resolved     _resolved: 'https://registry.npmjs.org/cloudcmd/-/cloudcmd-3.2.0.tgz' } ]
48 info install cloudcmd@3.2.0 into C:\Users\Администратор\AppData\Roaming\npm
49 info installOne cloudcmd@3.2.0
50 verbose installOne of cloudcmd to C:\Users\Администратор\AppData\Roaming\npm not in flight; installing
51 verbose lock using C:\Users\Администратор\AppData\Roaming\npm-cache\_locks\cloudcmd-17c66b7dd85dea10.lock for C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
52 verbose unlock done using C:\Users\Администратор\AppData\Roaming\npm-cache\_locks\cloudcmd-17c66b7dd85dea10.lock for C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
53 verbose stack Error: Appears to be a git repo or submodule.
53 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\npm-install-checks\index.js:139:15
53 verbose stack     at FSReqWrap.oncomplete (fs.js:95:15)
54 verbose cwd C:\Users\Администратор
55 error Windows_NT 6.2.9200
56 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "cloudcmd" "-g"
57 error node v0.12.4
58 error npm  v2.10.1
59 error path C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
60 error code EISGIT
61 error git Appears to be a git repo or submodule.
61 error git     C:\Users\Администратор\AppData\Roaming\npm\node_modules\cloudcmd
61 error git Refusing to remove it. Update manually,
61 error git or move it out of the way first.
62 verbose exit [ 1, true ]
```

**Comment by coderaiser** [comment]
По-сути ошибка та же: `Appears to be a git repo or submodule`.

Попробуйте lock-файл удалить `npm-cache\_locks\cloudcmd-17c66b7dd85dea10.lock`. Или он каждый раз заново создается?

Если это ничего не даст, остается установка `iojs` или переустановка `nodejs`.

**Comment by wormen** [comment]
да, lock файлы каждый раз создаются
nodejs и так переустанавливался, когда ставилась последняя версия ... на 0.12.2 не было таких проблем

**Comment by coderaiser** [comment]
Значит переустановка `npm` и установка `iojs`. Дело в том, что `Isaac Z. Schlueter` работает в основном с `iojs` (последняя версия соответственно постовляется как раз с ним), который, вопреки мнению многих, продолжает так же активно развиватся, как и раньше. А `nodejs`, к сожелению, так же плавно движется как и раньше, и вот такие проблемные места в нем исправляются гораздо медленее, чем в `iojs`. Где на следующий день после релиза могут выпустить патч.

**Comment by coderaiser** [comment]
Ошибка [Appears to be a git repo or submodule](https://github.com/npm/npm-install-checks/blob/master/index.js#L137) не имеет смысла, и не относится к `Cloud Commander`'у. Если ничего из описанного выше не работает - создайте issue в соответственных репозиториях (npm и nodejs).

**Comment by coderaiser** [comment]
Последнюю версию файлового менеджера, со всеми установленными зависимостями,  Вы всегда можете скачать с [раздела История Версий](http://ru.cloudcmd.io) либо со страницы [Releases](https://github.com/coderaiser/cloudcmd/releases).
Эти билды собираются как раз для таких случаев: когда нет возможности скачать через `npm`.
