### ISSUE TITLE
supervisor or systemd support ?

### ISSUE THREAD

**Issue by changchichung** [coderaiser/cloudcmd#385]
- **Version** (`cloudcmd -v`): v16.6.1
- **Node Version** `node -v`: v19.3.0
- **OS** (`uname -a` on Linux): ubuntu 22.04 x64
- **Browser name/version**: firefox/chrome
- **Used Command Line Parameters**: cloudcmd

I read about using systemd to start cloudcmd , but I failed to do so.
error log 
```
/home/mini/.nvm/versions/node/v19.3.0/lib/node_modules/cloudcmd/server/exit.js:3
const getMessage = (a) => a?.message || a;
                            ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:188:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
cloudcmd.service: Main process exited, code=exited, status=1/FAILURE
cloudcmd.service: Failed with result 'exit-code'.
cloudcmd.service: Scheduled restart job, restart counter is at 5.
Stopped Cloud Commander.
cloudcmd.service: Start request repeated too quickly.
cloudcmd.service: Failed with result 'exit-code'.
Failed to start Cloud Commander.
```
I also try to configure supervisor to start cloudcmd , and I get almost the same error
```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:188:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

I configure execstart with 
```
/home/mini/.nvm/versions/node/v19.3.0/bin/cloudcmd
```
is this correct ??

I can only start cloudcmd after I login to the remote machine , and I need to run cloudcmd as service .
any suggestions ??

**Comment by coderaiser** [comment]
Try to use node v18, v19 is unstable and can produce errors. This one related to syntax construction.

**Comment by changchichung** [comment]
I think it might related to I use nvm to manage nodejs version.
after uninstalling nvm and clean ~/.nvm  , ~/.npm 
I add nodejs v18 ppa and using apt to install nodejs/npm 
then ```sudo npm i cloudcmd -g```
now cloudcmd install to /usr/local/bin, and then I can use supervisor to manage it now.
