### ISSUE TITLE
v18.0.0 validateArgs is not a function Promise

### ISSUE THREAD

**Issue by frepke** [coderaiser/cloudcmd#417]
I've got the next errors in the latest dockerversion (v18.0.0 `image: coderaiser/cloudcmd:latest-alpine`):

```cloudcommander  | <!--
Thank you for reporting an issue. Please fill in the template below. If unsure
about something, just do as best as you're able.
-->

I've got the next errors in the latest dockerversion (v18.0.0 `image: coderaiser/cloudcmd:latest-alpine`):

```cloudcommander  | validateArgs is not a function Promise {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander  | validateArgs is not a function Promise {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander  | validateArgs is not a function Promise {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander  | validateArgs is not a function Promise {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander exited with code 1 {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander  | validateArgs is not a function Promise {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander  | validateArgs is not a function Promise {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander  | validateArgs is not a function Promise {
cloudcommander  |   <rejected> TypeError: validateArgs is not a function
cloudcommander  |       at main (file:///usr/src/app/bin/cloudcmd.mjs:169:25)
cloudcommander  | }
cloudcommander exited with code 1

**Comment by coderaiser** [comment]
Thanks! Just fixed in [v18.0.1](https://github.com/coderaiser/cloudcmd/releases/tag/v18.0.1) 🎉 . Is it works for you?

**Comment by frepke** [comment]
> Thanks! Just fixed in [v18.0.1](https://github.com/coderaiser/cloudcmd/releases/tag/v18.0.1) 🎉 . Is it works for you?

Yes, up and running again 👍🏻
