### ISSUE TITLE
Docker image for 5.7.0 is not working

### ISSUE THREAD

**Issue by wnkz** [coderaiser/cloudcmd#77]
* **Version** (`cloudcmd -v`): 5.7.0
* **Node Version** `node -v`: N/A
* **OS** (`uname -a` on Linux): N/A
* **Browser name/version**: N/A

Hello I think the latest docker image of cloudcmd is broken, here is what I have:

```
\> docker run --rm coderaiser/cloudcmd:5.7.0-alpine
module.js:471
    throw err;
    ^

Error: Cannot find module 'currify'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/node_modules/deepword/server_/index.js:9:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

5.6.2 version is working fine:
```
\> docker run --rm coderaiser/cloudcmd:5.6.2-alpine
url: http://localhost:8000/
update available: v5.7.0 (current: v5.6.2)
```

The problem remains the same wether or not I use the `-alpine` image.
Sorry I don't have the time to investigate what's wrong inside the container further more, I hope you'll find it easily.

**Comment by coderaiser** [comment]
Thank you, just updated images. Everything should work properly.
