### ISSUE TITLE
get a complain that .jshintrc was not existing

### ISSUE THREAD

**Issue by gbrault** [coderaiser/cloudcmd#81]
After install I got that  and was able to recover copying the file https://github.com/coderaiser/cloudcmd/blob/master/.jshintrc to /usr/lib/node_modules/cloudcmd/node_modules/dword/.jshintrc'

<< error lunching cloudcmd>>
pi@raspberrypi:~ $ cloudcmd
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/usr/lib/node_modules/cloudcmd/node_modules/dword/.jshintrc'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Function.sync (/usr/lib/node_modules/cloudcmd/node_modules/readjson/lib/readjson.js:28:23)
    at Object.<anonymous> (/usr/lib/node_modules/cloudcmd/node_modules/dword/lib/server.js:16:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

* **Version** (`cloudcmd -v`): v5.7.0
* **Node Version** `node -v`: v6.8.1
* **OS** (`uname -a` on Linux): Linux raspberrypi 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux
* **Browser name/version**: Version 53.0.2785.143 m (64-bit) in a remote Windows 10 machine

**Comment by coderaiser** [comment]
Fixed in [Dword v4.0.1](https://github.com/cloudcmd/dword/releases/tag/v4.0.1), landed in [Cloud Commander v5.7.1](https://github.com/coderaiser/cloudcmd/releases/tag/v5.7.1)
